### Paths of directories ###
_SHELL_SHARED_PATH=$_SHELL_CONFIG_PATH/shared
_SHELL_MODULES_PATH=$_SHELL_CONFIG_PATH/modules
_SHELL_MODULES_ARCHIVED_PATH=$_SHELL_CONFIG_PATH/modules_archived
_SHELL_APPS_PATH=$_SHELL_CONFIG_PATH/apps
_SHELL_SCRIPTS_PATH=$_SHELL_CONFIG_PATH/scripts
_CONFIG_PATH=$_SHELL_CONFIG_PATH/config
_REPOSITORY_PATH=~/repo

### Paths of files ###
_SHELL_MAIN_FILEPATH=$_SHELL_CONFIG_PATH/main.sh
_SHELL_AUTOSTART_FILEPATH=$_SHELL_CONFIG_PATH/autostart.sh
_SHELL_FWD_FILEPATH=$_SHELL_CONFIG_PATH/.fwd
_SHELL_PATH_FILEPATH=$_SHELL_CONFIG_PATH/path.sh
_USER_MODULE_FILEPATH=~/usermodule.sh
