### Paths of directories ###
__SHELL_CONFIG_PATH=~/shell_config
__SHELL_SHARED_PATH=$__SHELL_CONFIG_PATH/shared
__SHELL_MODULES_PATH=$__SHELL_CONFIG_PATH/modules
__SHELL_APPS_PATH=$__SHELL_CONFIG_PATH/apps
__SHELL_SOURCES_PATH=$__SHELL_CONFIG_PATH/sources
__SHELL_SCRIPTS_PATH=$__SHELL_CONFIG_PATH/scripts
__SHELL_FILES_PATH=$__SHELL_CONFIG_PATH/files
__CONFIG_PATH=$__SHELL_CONFIG_PATH/config
__REPOSITORY_PATH=~/REPOSITORY

### Paths of files ###
__SHELL_MAIN_FILEPATH=$__SHELL_CONFIG_PATH/main.sh
__SHELL_AUTOSTART_FILEPATH=$__SHELL_CONFIG_PATH/autostart.sh
__SHELL_FWD_FILEPATH=$__SHELL_CONFIG_PATH/.fwd
__SHELL_PATH_FILEPATH=$__SHELL_CONFIG_PATH/path.sh
__SHELL_NEW_FUNCTION_FILEPATH=$__SHELL_FILES_PATH/newfunction.sh
