### Paths of directories ###
_SHELL_CONFIG_PATH=~/shell_config
_SHELL_SHARED_PATH=$_SHELL_CONFIG_PATH/shared
_SHELL_MODULES_PATH=$_SHELL_CONFIG_PATH/modules
_SHELL_MODULES_ARCHIVED_PATH=$_SHELL_CONFIG_PATH/modules_archived
_SHELL_APPS_PATH=$_SHELL_CONFIG_PATH/apps
_SHELL_SCRIPTS_PATH=$_SHELL_CONFIG_PATH/scripts
_SHELL_FILES_PATH=$_SHELL_CONFIG_PATH/files
_CONFIG_PATH=$_SHELL_CONFIG_PATH/config
_OVERRIDE_MODULE_PATH=$_SHELL_MODULES_PATH/override
_REPOSITORY_PATH=~/_repository

### Paths of files ###
_SHELL_MAIN_FILEPATH=$_SHELL_CONFIG_PATH/main.sh
_SHELL_AUTOSTART_FILEPATH=$_SHELL_CONFIG_PATH/autostart.sh
_SHELL_FWD_FILEPATH=$_SHELL_CONFIG_PATH/.fwd
_SHELL_PATH_FILEPATH=$_SHELL_CONFIG_PATH/path.sh
_SHELL_NEW_FUNCTION_FILEPATH=$_SHELL_FILES_PATH/newfunction.sh
