BASH_CONFIG_PATH=~/bash_config
BASH_MODULES_PATH=$BASH_CONFIG_PATH/modules
BASH_APPS_PATH=$BASH_CONFIG_PATH/apps
BASH_SOURCES_PATH=$BASH_CONFIG_PATH/sources
BASH_SCRIPTS_PATH=$BASH_CONFIG_PATH/scripts
CONFIG_PATH=$BASH_CONFIG_PATH/config
REPOSITORY_PATH=~/REPOSITORY

# scripts / files
BASH_ALIASES_PATH=$BASH_CONFIG_PATH/aliases.sh
BASH_AUTOSTART_PATH=$BASH_CONFIG_PATH/autostart.sh
BASH_FWD_PATH=$BASH_CONFIG_PATH/.fwd
BASH_PATH_FILE=$BASH_CONFIG_PATH/path.sh
BASH_FILES_PATH=$BASH_CONFIG_PATH/files
BASH_NEW_FUNCTION_FILE=$BASH_FILES_PATH/newfunction.sh
