#!/usr/bin/env zsh

echo "Validating scripts..."
./validate.sh

# $? stores exit value of the last command
if [[ $? -ne 0 ]]
 then
  echo "Cannot validate scripts - something is wrong."
  exit 1
 else
  echo "Scripts validated successfully."
fi
