_help_util_server='Starts a python server on 7070'
_help__pull_cloned_apps='Pulls all cloned apps in app folder'
_help_util_upgrade=''
_help_util_bak='Renames a subject by adding current date'
_help_util_killall=''
_help_util_replaceinpath=''
_help_util_dockerstart='Starts a docker container with provided name'
_help_util_dockerip='Prints IP of provided docker container'
_help_util_ip=
_help_util_share=
_help_util_fixpermissions=
_help_util_findpath=
_help_util_writeimageinstructions=
_help_util_remountrw=
_help_util_ramdisk=
_help_util_screenshot=
_help_util_adduser=
_help_util_prefixallfiles=
_help_util_suffixallfiles=
_help_util_tar_compress=
_help_util_tar_extract=
