_help_sh_newfunction='Copies function template to clipboard'
_help_sh_newhelp='Copies help code line to clipboard'
_help_sh_newcheck='Copies check code line to clipboard'
_help_sh_newmodule='Creates a new module (modules/xxx/module.sh). Usage: sh-newmodule tst'
_help_sh_edit='Edits "module.sh" file from provided module. If no module is specified, then edits a main "module.sh" file'
_help_sh_edithelp='Edits "help.sh" file from provided module'
_help_sh_show='Shows "module.sh" file from provided module. If no module is specified, then shows a main "module.sh" file'
_help_sh_commit='Commits all changes in shell config directory'
_help_sh_push='Pushes all commits from shell config directory'
_help_sh_commitpush='Commits and pushes all changes from shell config directory'
_help_sh_revert=''
_help_sh_refresh=''
_help_sh_navigate='Navigates the shell config directory'
_help_sh_generatehelp='Generates help variables for file'
_help__pull_cloned_apps=
_help__getmodulepath=
_help__getmodulefilespath=
_help__editfile=
_help__filetoclipboard=
_help_sh_archivemodule=
_help_sh_source=
_help_sh_pull=
_help_sh_diff=
_help_sh_tig=
_help_sh_tis=
_help_sh_updatehelp=
_help_sh_validate=
_help_sh_st=
_help_sh_what='Shows all functions with given pattern'
_help_sh_newusermodule='Create a file for functions in user directory'
_help_sh_view=
