__gitmakediff='Creates a diff file from commits with provided pattern'
git_config='Sets up the git username/email. Usage: git-config "email@email.com" "User Name"'
git_parent='Finds parents of current branch'
git_branch='Creates local branches for all found remote branches with provided pattern'
git_deletebranches='Deletes all local branches except develop'
git_difftask=''
git_pushrefs='Git pushrefs to specified branch. Usage: git-pushrefs release_0.1'
