__help___gitmakediff='Creates a diff file from commits with provided pattern'
__help_git_config='Sets up the git username/email. Usage: git-config "email@email.com" "User Name"'
__help_git_parent='Finds parents of current branch'
__help_git_branch='Creates local branches for all found remote branches with provided pattern'
__help_git_deletebranches='Deletes all local branches except develop'
__help_git_difftask=''
__help_git_pushrefs='Git pushrefs to specified branch. Usage: git-pushrefs release_0.1'
