_help_uu_server='Starts a python server on 7070'
_help__pull_cloned_apps='Pulls all cloned apps in app folder'
_help_uu_upgrade='Upgrades from apt and shell config from Git'
_help_uu_bak='Renames a subject by adding current date'
_help_uu_killall='Kills all processes by name'
_help_uu_replaceinpath='Replaces all strings in the folders tree'
_help_uu_dockerstart='Starts a docker container with provided name'
_help_uu_dockerip='Prints IP of provided docker container'
_help_uu_ip=
_help_uu_share=
_help_uu_fixpermissions=
_help_uu_findpath=
_help_uu_writeimageinstructions=
_help_uu_remountrw=
_help_uu_ramdisk=
_help_uu_screenshot=
_help_uu_adduser=
_help_uu_prefixallfiles=
_help_uu_suffixallfiles=
_help_uu_tar_compress=
_help_uu_tar_extract=
_help_uu_checksum=
_help_functionrepeat=
_help_uu_copydate=
_help_uu_syslog='Shows the system log in lnav'
_help_uu_onyx=
_help_gpg_encrypt='i.e. gpg-encrypt dawidkotarba@email.pl text.txt'
_help_gpg_decrypt='i.e. gpg-decrypt text.txt.gpg'
_help_uu_tarball='Creates a tarball'
_help_uu_untarball='Unpacks the tarball'
_help_uu_suspend='Sleeps the computer'
